# Generated by Django 4.2.26 on 2026-03-21 19:40

from django.db import migrations, models
import recordings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=recordings.models.audio_upload_path)),
                ('text_local', models.CharField(max_length=500)),
                ('translation', models.CharField(max_length=500)),
                ('language', models.CharField(choices=[('yemba', 'Yemba'), ('douala', 'Douala'), ('ewondo', 'Ewondo')], max_length=20)),
                ('speaker_id', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
