# Generated by Django 4.2.26 on 2026-03-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_speakeridcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFileCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('next_index', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Compteur fichiers audio',
            },
        ),
    ]
