# Generated by Django 4.2.26 on 2026-03-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0005_audiofilecounter_per_speaker'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.UniqueConstraint(fields=('speaker_id', 'language', 'text_local'), name='uniq_recording_speaker_language_text_local'),
        ),
    ]
